version: 2

project_name: paddock

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: "asc"
  filters:
    exclude: ["^docs:", "^test:", "Merge pull request", "Merge branch", "go mod tidy"]

archives:
  - formats: [ "tar.gz" ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
    - goos: windows
      formats: [ "zip" ]
    files:
     - README.md
     - LICENSE.md

homebrew_casks:
  - name: paddock
    repository:
      owner: eepzii
      name: homebrew-tap
    homepage: "https://github.com/eepzii/paddock"
    description: "Short description of your tool"
    license: "MIT"

scoops:
  - repository:
      owner: eepzii
      name: scoop-bucket
    homepage: "https://github.com/eepzii/paddock"
    description: "Short description of your tool"
    license: "MIT"